#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["click>=8.1"]
# ///
"""Track task status from task cards, worker handoffs, and coordinator decisions.

    progress.py show                         # table on stdout
    progress.py show --write PROGRESS.md     # also regenerate PROGRESS.md
    progress.py ready                        # tasks whose dependencies are accepted
    progress.py set TASK-042 accepted --note "merged as 1a2b3c4"
    progress.py set TASK-043 rejected --note "leaks token in list response"

Worker status comes from handoffs/TASK-###.md (## Status); the coordinator's
review decision lives in tasks/status.json. A task counts as done only when the
coordinator has accepted it — a worker saying "Completed" is not acceptance.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import click

from taskcard import SHA_RE, TaskCard, sections, strip_comments, task_cards

DECISIONS = ["accepted", "rejected", "escalated", "in-progress", "cancelled"]


def load_decisions(tasks_dir: Path) -> dict[str, dict]:
    path = tasks_dir / "status.json"
    return json.loads(path.read_text()) if path.exists() else {}


def handoff_info(handoffs_dir: Path, task_id: str) -> tuple[str, str]:
    path = handoffs_dir / f"{task_id}.md"
    if not path.exists():
        return "-", "-"
    secs = {k: strip_comments(v) for k, v in sections(path.read_text()).items()}
    status = (secs.get("Status") or "?").splitlines()[0].strip()
    m = SHA_RE.search(secs.get("Commit", ""))
    return status, m.group(0)[:10] if m else "-"


def rows(tasks_dir: Path, handoffs_dir: Path) -> list[dict]:
    decisions = load_decisions(tasks_dir)
    out = []
    for card in task_cards(tasks_dir):
        worker, sha = handoff_info(handoffs_dir, card.task_id)
        d = decisions.get(card.task_id, {})
        out.append(
            {
                "card": card,
                "model": card.model or "?",
                "worker": worker,
                "commit": sha,
                "decision": d.get("decision", "pending"),
                "note": d.get("note", ""),
            }
        )
    return out


def ready(all_rows: list[dict]) -> list[TaskCard]:
    accepted = {r["card"].task_id for r in all_rows if r["decision"] == "accepted"}
    return [
        r["card"]
        for r in all_rows
        if r["decision"] == "pending" and r["worker"] == "-" and set(r["card"].depends_on) <= accepted
    ]


def render(all_rows: list[dict]) -> str:
    lines = [
        "| Task | Title | Model | Depends on | Worker status | Commit | Decision | Note |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in all_rows:
        c: TaskCard = r["card"]
        lines.append(
            f"| {c.task_id} | {c.title} | {r['model']} | {', '.join(c.depends_on) or '—'} | "
            f"{r['worker']} | {r['commit']} | {r['decision']} | {r['note']} |"
        )
    counts: dict[str, int] = {}
    for r in all_rows:
        counts[r["decision"]] = counts.get(r["decision"], 0) + 1
    summary = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
    return "\n".join(lines) + f"\n\n{len(all_rows)} task(s): {summary or 'none'}\n"


@click.group()
@click.option("--tasks-dir", type=click.Path(path_type=Path), default=Path("tasks"), show_default=True)
@click.option("--handoffs-dir", type=click.Path(path_type=Path), default=Path("handoffs"), show_default=True)
@click.pass_context
def cli(ctx: click.Context, tasks_dir: Path, handoffs_dir: Path) -> None:
    ctx.obj = {"tasks": tasks_dir, "handoffs": handoffs_dir}


@cli.command()
@click.option("--write", type=click.Path(path_type=Path), help="Also write the table to this file.")
@click.pass_obj
def show(obj: dict, write: Path | None) -> None:
    """Print the status table."""
    table = render(rows(obj["tasks"], obj["handoffs"]))
    click.echo(table, nl=False)
    if write:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        write.write_text(f"# PROGRESS\n\n_Generated by progress.py at {stamp}._\n\n{table}")


@cli.command("ready")
@click.pass_obj
def ready_cmd(obj: dict) -> None:
    """List tasks that can be dispatched now (dependencies accepted, not started)."""
    for card in ready(rows(obj["tasks"], obj["handoffs"])):
        click.echo(f"{card.task_id}\t{card.model or '?'}\t{card.path}")


@cli.command("set")
@click.argument("task_id")
@click.argument("decision", type=click.Choice(DECISIONS))
@click.option("--note", default="")
@click.pass_obj
def set_cmd(obj: dict, task_id: str, decision: str, note: str) -> None:
    """Record the coordinator's DECISION for TASK_ID."""
    task_id = task_id.upper()
    known = {c.task_id for c in task_cards(obj["tasks"])}
    if task_id not in known:
        raise click.ClickException(f"{task_id} has no task card in {obj['tasks']}")
    decisions = load_decisions(obj["tasks"])
    decisions[task_id] = {
        "decision": decision,
        "note": note,
        "at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    (obj["tasks"] / "status.json").write_text(json.dumps(decisions, indent=2, sort_keys=True) + "\n")
    click.echo(f"{task_id}: {decision}")


if __name__ == "__main__":
    cli()
